name: SwagLabs Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: |
          CI=true npx playwright test || echo "Tests failed, review logs."
          
          # Check if the report directory exists
          if [ -d test-results ]; then
            echo "artifact_exists=true" >> $GITHUB_ENV
          else
            echo "artifact_exists=false" >> $GITHUB_ENV
          fi

      - name: Upload Test Artifacts
        if: failure() && env.artifact_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: SwagLabs-Playwright-Test-Artifacts
          path: test-results/
